const BUILTINS = {
  end({ error }) {
    error(`Do not use the end command in Dragonsbreath. Use significant whitespacing`);
  },

  lock({ children, transpile }) {
    if (children) {
      return [
        'lock',
        transpile(children),
        'release',
      ];
    }

    return 'lock';
  },

  script({ parameters, error, transpile, children, setCurrentScript }) {
    if (parameters.length !== 1) {
      error(`The "script" command must take exactly one parameter`);
    }

    if (parameters[0].type !== 'token') {
      error(`The parameter to the "script" command must be a token.`)
    }

    setCurrentScript(parameters[0].value);

    return [
      `@ Generated by Dragonsbreath`,
      `${parameters[0].value}::`,
      transpile(children),
      'end',
    ];
  },

  // TODO needs to support clustering say blocks together if they're adjacent
  say({ parameters, error, transpileParameter, getExternalName, addExternal, currentScript }) {
    if (!parameters || !parameters.length) {
      error(`The "say" command must take at least one parameter`)
    }

    const [text, msgbox] = parameters;
    const msgboxOrDefault = msgbox || { 
      type: 'constant', 
      value: 'MSGBOX_DEFAULT' 
    };

    const externalName = getExternalName(currentScript, 'text');
    addExternal([
      `@ Generated by Dragonsbreath. This is a child script of ${currentScript}`,
      `${externalName}:`,
      `.string ${transpileParameter(text)}`
    ]);

    return `msgbox ${externalName}, ${transpileParameter(msgboxOrDefault)}`;
  }
};

module.exports = BUILTINS;